#   الاسم: شهد عبدالقادر السعيد عبدالقادر عيد
# الفرقة: تالتة عام








   



Create a random tensor with shape (7, 7)

In [10]:
import torch

# Set the random seed
torch.manual_seed(0)

# Create a random tensor of shape (7, 7)
tensor = torch.rand(7, 7)

print(tensor)

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])


 Perform a matrix multiplication on the tensor from above with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor

In [12]:
import torch

# Create the first random tensor of shape (7, 7)
tensor1 = torch.rand(7, 7)

# Create the second random tensor of shape (1, 7)
tensor2 = torch.rand(1, 7)

# Transpose the second tensor to make it (7, 1)
tensor2_t = tensor2.T  # or tensor2.transpose(0, 1)

# Perform matrix multiplication
result = torch.matmul(tensor1, tensor2_t)
print("\nResult:\n", result)


Result:
 tensor([[1.1061],
        [0.9868],
        [1.8999],
        [0.7716],
        [1.3174],
        [1.6353],
        [1.7395]])


Set the random seed to 0 and do 2 & 3 over **again**

In [13]:
# Set the random seed
torch.manual_seed(0)

# Create a random tensor of shape (1, 7)
tensor2 = torch.rand(1, 7)

# Transpose the second tensor to shape (7, 1)
tensor2_transposed = tensor2.t()

# Perform matrix multiplication
result_tensor = torch.matmul(tensor, tensor2_transposed)

print(result_tensor)

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])


Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)**bold text**

In [14]:
import torch

# Set the random seed on the GPU
if torch.cuda.is_available():
    torch.cuda.manual_seed(0)
    print("Random seed set on GPU.")
else:
    print("GPU not available. Random seed not set on GPU.")

GPU not available. Random seed not set on GPU.


In [17]:
import torch

if torch.cuda.is_available():
    # Create a tensor on the GPU
    gpu_tensor = torch.rand(3, 3, device='cuda')
    print("Tensor created on GPU:\n", gpu_tensor)
else:
    print("GPU not available. Cannot create tensor directly on GPU.")

GPU not available. Cannot create tensor directly on GPU.


Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed)**bold text**

In [18]:
import torch

# Set the random seed
torch.manual_seed(1234)

# Create two random tensors of shape (2, 3)
tensor1 = torch.rand(2, 3)
tensor2 = torch.rand(2, 3)

print("CPU Tensor 1:\n", tensor1)
print("CPU Tensor 2:\n", tensor2)

# Send tensors to the GPU if available
if torch.cuda.is_available():
    gpu_tensor1 = tensor1.to('cuda')
    gpu_tensor2 = tensor2.to('cuda')
    print("\nGPU Tensor 1:\n", gpu_tensor1)
    print("GPU Tensor 2:\n", gpu_tensor2)
else:
    print("\nGPU not available. Tensors remain on CPU.")

CPU Tensor 1:
 tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])
CPU Tensor 2:
 tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]])

GPU not available. Tensors remain on CPU.


 Perform a matrix multiplication on the tensors you created in above
  (again, you may have to adjust the shapes of one of the tensors)

In [19]:
import torch

# Assuming tensor1 and tensor2 are already defined from the previous cell

# Check if tensors are on GPU and perform multiplication accordingly
if torch.cuda.is_available():
    # Tensors are on GPU
    # Transpose the second tensor to shape (3, 2)
    gpu_tensor2_transposed = gpu_tensor2.t()
    # Perform matrix multiplication on GPU
    gpu_result = torch.matmul(gpu_tensor1, gpu_tensor2_transposed)
    print("GPU Matrix Multiplication Result:\n", gpu_result)
else:
    # Tensors are on CPU
    # Transpose the second tensor to shape (3, 2)
    tensor2_transposed = tensor2.t()
    # Perform matrix multiplication on CPU
    cpu_result = torch.matmul(tensor1, tensor2_transposed)
    print("CPU Matrix Multiplication Result:\n", cpu_result)

CPU Matrix Multiplication Result:
 tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])


Find the maximum and minimum values of the output of above

In [24]:
import torch

# Assuming 'cpu_result' or 'gpu_result' exists from the previous cell
if torch.cuda.is_available():
    if 'gpu_result' in locals():
        max_value = torch.max(gpu_result)
        min_value = torch.min(gpu_result)
        print("Maximum value of the result tensor:", max_value)
        print("Minimum value of the result tensor:", min_value)
    else:
        print("GPU result tensor not found.")
else:
    if 'cpu_result' in locals():
        max_value = torch.max(cpu_result)
        min_value = torch.min(cpu_result)
        print("Maximum value of the result tensor:", max_value)
        print("Minimum value of the result tensor:", min_value)
    else:
        print("CPU result tensor not found.")

Maximum value of the result tensor: tensor(0.5617)
Minimum value of the result tensor: tensor(0.3647)


Find the maximum and minimum index values of the output of above

In [25]:
import torch

# Assuming 'cpu_result' or 'gpu_result' exists from the previous cell
if torch.cuda.is_available():
    if 'gpu_result' in locals():
        max_index = torch.argmax(gpu_result)
        min_index = torch.argmin(gpu_result)
        print("Index of the maximum value:", max_index)
        print("Index of the minimum value:", min_index)
    else:
        print("GPU result tensor not found.")
else:
    if 'cpu_result' in locals():
        max_index = torch.argmax(cpu_result)
        min_index = torch.argmin(cpu_result)
        print("Index of the maximum value:", max_index)
        print("Index of the minimum value:", min_index)
    else:
        print("CPU result tensor not found.")

Index of the maximum value: tensor(3)
Index of the minimum value: tensor(0)


Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape

In [26]:
import torch

# Set the random seed
torch.manual_seed(7)

# Create a random tensor with shape (1, 1, 1, 10)
tensor1 = torch.rand(1, 1, 1, 10)

print("First Tensor:\n", tensor1)
print("Shape of the first tensor:", tensor1.shape)

# Create a new tensor with all 1 dimensions removed
tensor2 = torch.squeeze(tensor1)

print("\nSecond Tensor (squeezed):\n", tensor2)
print("Shape of the second tensor:", tensor2.shape)

First Tensor:
 tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
Shape of the first tensor: torch.Size([1, 1, 1, 10])

Second Tensor (squeezed):
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
Shape of the second tensor: torch.Size([10])
